name: Build CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Build Nuke
      run: dotnet build './build' /nodeReuse:false --configuration Release
    - name: Build Program
      run: dotnet run --project build --target Publish  --NugetSource "https://nuget.pkg.github.com/windischb/index.json" --NugetUsername "windischb" --NugetPassword ${{secrets.NugetApiKey}}
