name: Build CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Build Nuke
      run: dotnet build './build' /nodeReuse:false --configuration Release
    - name: Build Program
      run: dotnet run --project build --target Publish --ApiKey ${{secrets.GITHUB_TOKEN}} --NugetFeed https://nuget.pkg.github.com/windischb/index.json
