name: Build CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core 2.2.401
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.401'

    - name: Setup .NET Core 3.0.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'

    
    - name: Build Nuke
      run: dotnet build './build' /nodeReuse:false --configuration Release --framework netcoreapp2.0

    - name: Build Program
      run: build.sh
