name: Build CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.0.100'
    - name: Build Nuke
      run: dotnet build './build' /nodeReuse:false --configuration Release
    - name: Build Program
      run: dotnet run --project build --target Compile
