name: Build CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core 3.0.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    
    - name: Prepare Tools
      run: dotnet tool install --global GitVersion.Tool
    
    - name: Check Version
      run: dotnet gitversion

    - name: Build Program
      run: dotnet build TryGitActions.Cmd -c Release -o output
