name: Build CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Nuke
      run: dotnet build './build' /nodeReuse:false --configuration Release
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/windischb/index.json -Username windischb -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Build Program
      run: dotnet run --project build --target Publish --NugetFeed https://nuget.pkg.github.com/windischb/index.json
